import { Project } from './types';

export const sampleProject: Project = {
  id: 'sample-001',
  title: 'The WhatsApp Bird',
  format: '9:16',
  duration: '60s',
  platform: 'Instagram',
  targetAudience: 'Gen Z / Millennials overwhelmed by notifications',
  mainEmotion: 'Amused recognition → quiet dread',
  mainMessage: 'A small notification is a massive event inside your nervous system.',
  creativeTension: 'The phone is tiny. Its effect on the creature is jungle-scale.',
  hook: 'A giant fluffy bird-monster casts a shadow over the jungle. It\'s looking for a phone.',
  payoff: 'The bird touches the screen. The whole jungle explodes with notification energy. It looks victorious. And trapped.',
  visualPromise: 'Cinematic jungle scale meets WhatsApp green glow. Cute monster, enormous feeling.',
  tools: 'Midjourney, Runway, ElevenLabs, Suno, CapCut',
  notes: 'Keep it funny first. Let the dread arrive slowly. The bird should feel relatable, not scary.',
  idea: {
    messyIdea:
      'A giant cute green WhatsApp bird monster flies above a cinematic jungle, searching for a phone that acts as the source of distraction. It is angry but fluffy and round. The moment its beak touches the phone screen, the whole jungle lights up with notification energy. The story is about the way tiny notifications become huge mental events.',
    randomImages:
      'Morning mist. Giant shadow on trees. Green feathers. Glowing screen in forest floor. Firefly-like UI particles. Beak closeup. Jungle exploding with light.',
    references:
      'Where The Wild Things Are aesthetic. Studio Ghibli creature design. Black Mirror notification horror. Jonah Hill-level emotional expressiveness in animal form.',
    wants:
      'Epic cinematic scale. Creature that feels immediately recognizable. Humor before dread. Sound design that mirrors phone UX.',
    avoid:
      'Corporate explainer tone. Literal WhatsApp branding. Jump scares. Making the phone a villain explicitly.',
    fears:
      'It feels like an ad. The metaphor is too obvious. The bird looks scary instead of cute. The ending lands flat.',
    excitement:
      'The moment the jungle lights up. The POV from inside the phone. The bird\'s face when it realizes it\'s both victorious and trapped.',
  },
  insight: {
    coreInsight:
      'Attention is not stolen loudly. It arrives cute, useful and familiar — then becomes massive inside the nervous system.',
    emotionalGoal:
      'The viewer laughs first, then feels slightly attacked. Then recognizes themselves in the bird.',
    viewerTakeaway:
      'That silly little ping rewires your whole brain. You\'re the bird. The jungle is your nervous system.',
    conflict:
      'The creature is free and powerful in its natural world — until the phone makes it its servant.',
    metaphor:
      'A tiny phone = a jungle-scale monster ecosystem. The notification is not the distraction — the response is.',
    tension:
      'The app feels small in your hand but it\'s enormous inside your nervous system.',
    whyItWorks:
      'It externalizes an invisible feeling. The monster is cute so you trust it. Then it mirrors you back to yourself.',
    risks:
      'Over-explaining the metaphor. Making the bird too scary. Losing the humor before the dread lands.',
    oneSentenceSummary:
      'A giant fluffy bird-monster destroys its own jungle just to touch a phone screen.',
  },
  mindMapNodes: [
    {
      id: 'node-01',
      label: 'Core Idea',
      type: 'core_idea',
      content: 'Notifications are tiny in the hand but massive in the nervous system.',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-02', 'node-03'],
    },
    {
      id: 'node-02',
      label: 'The Bird Monster',
      type: 'character',
      content: 'Giant, green, fluffy, round. Angry but adorable. Instantly recognizable as "notification energy."',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-01', 'node-04'],
    },
    {
      id: 'node-03',
      label: 'Nervous System = Jungle',
      type: 'visual_metaphor',
      content: 'The jungle is the viewer\'s inner world. The bird is the notification response. Scale is the trick.',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-01', 'node-06'],
    },
    {
      id: 'node-04',
      label: 'Victorious and Trapped',
      type: 'emotion',
      content: 'The bird gets what it wants — and immediately loses something more important.',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-02', 'node-07'],
    },
    {
      id: 'node-05',
      label: 'Phone as Prey',
      type: 'conflict',
      content: 'The bird hunts the phone like prey. But the phone hunts back.',
      strength: 'medium',
      isWeird: true,
      connectedTo: ['node-02', 'node-03'],
    },
    {
      id: 'node-06',
      label: 'Notification Fireflies',
      type: 'visual_metaphor',
      content: 'UI particles become fireflies. The jungle becomes a notification feed. Beautiful and overwhelming.',
      strength: 'high',
      isWeird: true,
      connectedTo: ['node-03', 'node-07'],
    },
    {
      id: 'node-07',
      label: 'Phone POV Shot',
      type: 'production_note',
      content: 'The most powerful shot: camera IS the phone. The bird\'s beak fills the screen. We are the device.',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-04', 'node-06'],
    },
    {
      id: 'node-08',
      label: 'Sound = Escalation',
      type: 'sound_world',
      content: 'Start with jungle silence. Then one ping. Then chaos. The sound design IS the story.',
      strength: 'high',
      isWeird: false,
      connectedTo: ['node-01', 'node-06'],
    },
  ],
  concepts: [
    {
      id: 'concept-01',
      title: 'The Ping',
      directionType: 'safe',
      logline: 'A bird-monster hunts a phone and gets exactly what it asked for — at the cost of its freedom.',
      whyItWorks: 'Clear cause and effect. Visually strong. Humor first, meaning second.',
      character: 'The WhatsApp Bird: giant, green, fluffy, round. Endearingly furious.',
      conflict: 'The bird is drawn to the phone but the phone transforms the jungle the moment they connect.',
      visualWorld: 'Cinematic jungle. Warm morning light. One glowing screen. Then green explosion.',
      beginning: 'Peaceful jungle. Giant shadow. The bird descends.',
      middle: 'The bird spots the phone. Close-up pursuit. Phone POV as beak approaches.',
      end: 'Jungle erupts. Bird looks victorious. Then trapped. Smash cut to silence.',
      punch: 'The notification sound played at jungle volume.',
      risks: 'Too literal. Too safe. May read as an ad.',
      productionDifficulty: 'Medium',
      selected: false,
    },
    {
      id: 'concept-02',
      title: 'The Nervous System Film',
      directionType: 'cinematic',
      logline: 'Inside every ping, a whole world responds. This is that world.',
      whyItWorks: 'Creates genuine wonder. The emotional arc hits hard. Cinematic scale justifies the format.',
      character: 'The Bird as the viewer\'s inner self — magnificent, distracted, enslaved.',
      conflict: 'Freedom vs. compulsion. Natural world vs. digital signal.',
      visualWorld: 'Jungle as mind. Roots as nerves. Light pulses as dopamine. Scale is everything.',
      beginning: 'The bird soars in silence over a vast jungle. We feel its freedom.',
      middle: 'The phone glows below. The bird cannot resist. Slow descent. The world holds its breath.',
      end: 'Contact. Eruption. The jungle transforms. The bird is magnificent and imprisoned.',
      punch: 'Silence after the explosion. Then one more ping.',
      risks: 'Too slow. Too art-house. May lose audience before the payoff.',
      productionDifficulty: 'High',
      selected: true,
    },
    {
      id: 'concept-03',
      title: 'Bird vs. Screen',
      directionType: 'weird',
      logline: 'What if the phone was sentient and it wanted to be found?',
      whyItWorks: 'Unpredictable. Subverts expectation. The weird reversal makes people rewatch.',
      character: 'The Bird is the victim. The Phone is the predator. The jungle conspires.',
      conflict: 'Is the bird hunting the phone — or is the phone hunting the bird?',
      visualWorld: 'Jungle with a hidden grid. Trees that look slightly wrong. Light that moves wrong.',
      beginning: 'The bird hunts. The phone hides badly. Almost like it wants to be found.',
      middle: 'Every time the bird gets close, the phone \'glitches\' closer. The jungle is the trap.',
      end: 'The bird touches the phone. Realizes it was placed there. The notification was from itself.',
      punch: 'The message reads: \'You have been online for 6 hours.\'',
      risks: 'Too conceptual. May not land without context. Needs perfect execution.',
      productionDifficulty: 'Very High',
      selected: false,
    },
  ],
  beats: [
    {
      id: 'beat-01',
      beatNumber: 1,
      duration: '0:00–0:08',
      role: 'hook',
      whatWeSee: 'Quiet jungle. Morning mist. A massive shadow moves across the canopy.',
      whatWeHear: 'Deep jungle ambience. Then — silence. Then a distant low rumble.',
      whatChanges: 'Calm → unease. Something huge is coming.',
      emotion: 'Curiosity + slight tension',
      storyPurpose: 'Establish world. Signal scale. Hook viewer before the character is revealed.',
      visualStyle: 'Cinematic wide. Slow dolly in. Warm morning light. Deep greens.',
    },
    {
      id: 'beat-02',
      beatNumber: 2,
      duration: '0:08–0:18',
      role: 'setup',
      whatWeSee: 'The giant fluffy green bird monster flies above the jungle. Round. Huge. Furious. Adorable.',
      whatWeHear: 'Giant wing flaps. Distant frustrated bird sounds. Faint notification pings in the distance.',
      whatChanges: 'Unknown threat → ridiculous lovable monster. Tone shift to humor.',
      emotion: 'Delight + recognition',
      storyPurpose: 'Introduce character. Establish that it\'s funny before it\'s scary. Set up the hunt.',
      visualStyle: 'Low angle looking up. Bird silhouetted against sky. Then close on its face: furious but round.',
    },
    {
      id: 'beat-03',
      beatNumber: 3,
      duration: '0:18–0:30',
      role: 'escalation',
      whatWeSee: 'The bird spots a glowing phone on the forest floor. Dives. Eyes locked. Nothing else exists.',
      whatWeHear: 'The notification ping gets louder. The bird\'s breathing quickens. The jungle goes quiet.',
      whatChanges: 'Free flight → focused compulsion. The hunt begins.',
      emotion: 'Excitement → obsession',
      storyPurpose: 'Establish the conflict. The phone is magnetic. The bird cannot choose not to respond.',
      visualStyle: 'Intercut between bird POV and phone glow. Speed increases. Lens compression.',
    },
    {
      id: 'beat-04',
      beatNumber: 4,
      duration: '0:30–0:40',
      role: 'transformation',
      whatWeSee: 'Extreme close-up. Camera is the phone. The bird\'s beak fills the frame. Time slows.',
      whatWeHear: 'Single heartbeat. Wind. The whole world holds its breath.',
      whatChanges: 'Hunter → the hunted. We are the phone. The beak is inevitable.',
      emotion: 'Tension → inevitability',
      storyPurpose: 'POV reversal. We become the device. The viewer recognizes themselves.',
      visualStyle: 'Phone POV. Giant beak descending. The bird\'s eyes are desperate and focused.',
    },
    {
      id: 'beat-05',
      beatNumber: 5,
      duration: '0:40–0:52',
      role: 'reveal',
      whatWeSee: 'Contact. The jungle erupts. Notification energy — fireflies, light pulses, UI particles — floods everything.',
      whatWeHear: 'WhatsApp ping at jungle volume. Then a cascade of notification sounds. Then silence.',
      whatChanges: 'Natural world → digital world. The jungle is now a notification feed.',
      emotion: 'Wonder → recognition → slight dread',
      storyPurpose: 'Payoff of the visual metaphor. The nervous system becomes visible. Small ping = massive event.',
      visualStyle: 'Wide reveal. Green glow floods frame. Bird at center, surrounded by light and sound.',
    },
    {
      id: 'beat-06',
      beatNumber: 6,
      duration: '0:52–1:00',
      role: 'punch',
      whatWeSee: 'Wide shot. The bird stands in the glowing jungle. It looks victorious. Then confused. Then trapped.',
      whatWeHear: 'One more ping. Then silence.',
      whatChanges: 'Victory → entrapment. The bird got what it wanted. It lost what it had.',
      emotion: 'Humor → recognition → quiet melancholy',
      storyPurpose: 'Land the meaning. The viewer laughs and then feels slightly called out.',
      visualStyle: 'Pull back slowly. Bird shrinks in frame. Jungle glowing around it. Smash cut to black.',
    },
  ],
  shots: [
    {
      id: 'shot-01',
      shotNumber: 1,
      duration: '4s',
      shotType: 'Wide',
      cameraAngle: 'Eye level',
      cameraMovement: 'Slow dolly forward',
      location: 'Jungle canopy — morning',
      character: '',
      action: 'Shadow moves across the trees',
      whatWeSee: 'Quiet jungle. Morning mist hangs between trees. A massive shadow glides across the canopy from left to right.',
      whatWeHear: 'Deep ambient jungle sounds. Wind. Distant birds. Then — silence.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'Wind. Leaf movement. Distant bird calls fading out.',
      musicNote: 'Sub-bass tone entering slowly.',
      visualStyle: 'Cinematic. Rich deep greens. Golden morning light rays through mist.',
      lighting: 'Golden hour morning. Dappled light through canopy.',
      color: 'Deep emerald greens, warm gold highlights, cool shadow areas.',
      composition: 'Trees frame the center. Shadow moves through middle third. Sky barely visible.',
      imagePrompt: 'Cinematic jungle canopy at dawn, morning mist between ancient trees, golden light rays filtering through dense foliage, massive shadow gliding across the treetops, ultra-wide establishing shot, photorealistic, 9:16 vertical, deep green and gold palette, atmospheric depth, no characters visible yet',
      videoPrompt: 'Slow dolly push into cinematic jungle canopy, morning mist drifting, golden light filtering through leaves, a massive unseen shadow gliding left to right across the treetops, 4 seconds, cinematic pacing, atmospheric and mysterious',
      negativePrompt: 'text, logos, cartoon, flat, low quality, bright midday light, no mist, crowded composition',
      tool: 'Midjourney + Runway',
      status: 'prompt_ready',
      notes: 'This shot must establish epic scale before the bird is revealed.',
    },
    {
      id: 'shot-02',
      shotNumber: 2,
      duration: '5s',
      shotType: 'Medium Wide',
      cameraAngle: 'Low angle',
      cameraMovement: 'Static then slow tilt up',
      location: 'Above jungle canopy',
      character: 'WhatsApp Bird Monster',
      action: 'Flying above jungle, looking furious and adorable',
      whatWeSee: 'A giant green fluffy round bird monster flies above the jungle. It is enormous. It is furious. It is unbearably cute.',
      whatWeHear: 'Giant wing flaps. Low frustrated bird vocalization.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'Heavy wing flaps. Frustrated bird sounds. Faint notification ping in distance.',
      musicNote: 'Low orchestral theme begins. Slightly comedic but cinematic.',
      visualStyle: 'Low hero angle. Bird silhouetted against sky first, then full color reveal.',
      lighting: 'Sky light from above. Ambient jungle green from below.',
      color: 'Bright WhatsApp green feathers, sky blue background, warm gold belly.',
      composition: 'Bird fills upper two-thirds of frame. Jungle below. Sky above.',
      imagePrompt: 'Giant fluffy round green bird monster flying above cinematic jungle, massive and adorable, furious expression, WhatsApp green feathers, round soft body, enormous wings, low angle hero shot looking up from jungle level, cinematic lighting, photorealistic creature design, 9:16 vertical',
      videoPrompt: 'Low angle shot of giant fluffy green round bird monster flying powerfully above jungle canopy, 5 seconds, slow tilt up from jungle to bird silhouette against sky, creature looks both enormous and adorably round, frustrated expression, cinematic motion, deep wing flaps',
      negativePrompt: 'scary, menacing, sharp angular design, small creature, flat colors, cartoon style, low resolution, blurry',
      tool: 'Midjourney + Runway',
      status: 'prompt_ready',
      notes: 'The bird must read as CUTE before SCARY. Round shapes, soft textures. Pixar-adjacent in feel.',
    },
    {
      id: 'shot-03',
      shotNumber: 3,
      duration: '5s',
      shotType: 'Medium',
      cameraAngle: 'Bird POV looking down',
      cameraMovement: 'Slow push down / slight shake',
      location: 'Forest floor below',
      character: 'WhatsApp Bird Monster (POV)',
      action: 'Spots phone. Eyes lock in.',
      whatWeSee: 'From the bird\'s perspective, looking down. A glowing phone sits on the forest floor between roots. It pulses with soft green light.',
      whatWeHear: 'The notification ping gets louder. The bird\'s breathing quickens.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'WhatsApp ping, close and clear. Heavy bird breathing. Wing movement slows.',
      musicNote: 'Music stops. Only breathing and ping.',
      visualStyle: 'POV shot looking down from height. Slight hand-held feel. Phone glowing below.',
      lighting: 'Warm ambient jungle. The phone is the only bright source.',
      color: 'Dark forest floor, roots and earth tones, single bright green glow from phone.',
      composition: 'Phone in center third of frame. Roots and earth around it. Dark edges.',
      imagePrompt: 'Bird\'s eye POV looking down at forest floor, glowing phone screen between ancient tree roots, soft green notification glow illuminating the earth, jungle darkness around it, cinematic composition, photorealistic, 9:16 vertical, deep shadows with single light source',
      videoPrompt: 'Slow push-in POV shot looking down from great height toward forest floor, glowing phone between tree roots pulses with green notification light, 5 seconds, slight organic camera movement, phone gets larger as we descend, cinematic atmosphere',
      negativePrompt: 'flat lighting, multiple phones, cluttered frame, cartoonish, daylight, obvious brand logos',
      tool: 'Midjourney + Runway',
      status: 'generated',
      notes: 'The phone should feel like a treasure or a trap. Both simultaneously.',
    },
    {
      id: 'shot-04',
      shotNumber: 4,
      duration: '6s',
      shotType: 'Extreme Close-Up',
      cameraAngle: 'Phone POV looking up',
      cameraMovement: 'Static — we are the phone',
      location: 'Forest floor — phone perspective',
      character: 'WhatsApp Bird Monster',
      action: 'Beak descending toward screen',
      whatWeSee: 'We are the phone. The sky is above us. Roots and earth at edges. The bird\'s giant beak descends slowly, filling the frame.',
      whatWeHear: 'Single heartbeat. Wind. Silence.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'Heartbeat. Wind. Then complete silence.',
      musicNote: 'All music drops out. Only heartbeat.',
      visualStyle: 'Ground-level POV. Bird beak fills top of frame. Cinematic slow motion.',
      lighting: 'Sky light from above. Screen glow illuminating beak from below.',
      color: 'Green beak illuminated from below with soft phone-screen light. Sky above.',
      composition: 'Beak centered and dominant. Sky in upper half. Earth edges at bottom. Extreme depth.',
      imagePrompt: 'Phone screen POV looking up at giant green bird beak descending from above, beak fills upper frame, cinematic jungle in background, sky visible, soft green screen glow illuminating the beak from below, extreme close-up, photorealistic, cinematic tension, 9:16 vertical',
      videoPrompt: 'Static phone POV shot looking straight up, giant fluffy green bird beak slowly descends from above in slow motion, 6 seconds, beak grows to fill frame, sky and jungle visible around edges, phone screen glow illuminates beak from below, breathtaking tension',
      negativePrompt: 'fast movement, multiple beaks, distorted anatomy, scary feathers, cartoon look, blurry beak, wrong scale',
      tool: 'Midjourney + Runway',
      status: 'needs_refinement',
      notes: 'This is the hero shot. The POV reversal. We must become the device.',
    },
    {
      id: 'shot-05',
      shotNumber: 5,
      duration: '8s',
      shotType: 'Wide',
      cameraAngle: 'Eye level',
      cameraMovement: 'Slow pull back + tilt up',
      location: 'Jungle — full environment',
      character: 'WhatsApp Bird Monster',
      action: 'Beak touches phone. Jungle erupts with light.',
      whatWeSee: 'Contact. The entire jungle erupts. Notification fireflies. UI light pulses. Green glow floods everything. The bird stands in the center of the explosion.',
      whatWeHear: 'WhatsApp ping at jungle volume. Then cascade of notification sounds. Then silence.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'Massive WhatsApp ping. Cascade of UI sounds. Light explosion. Then silence.',
      musicNote: 'Orchestral swell then drop to silence.',
      visualStyle: 'Epic wide reveal. Green explosion of light. Cinematic grandeur.',
      lighting: 'Full green notification glow. Fills the entire jungle.',
      color: 'WhatsApp green dominates. Firefly white-gold. Deep shadow at edges.',
      composition: 'Bird at center. Jungle fills frame. Light radiates from center.',
      imagePrompt: 'Wide cinematic shot of jungle erupting with green notification light, giant fluffy green bird monster at center, notification fireflies and UI light particles filling the air, WhatsApp green glow flooding the entire environment, cinematic epic scale, photorealistic, 9:16 vertical',
      videoPrompt: 'Slow pull back and tilt up as jungle erupts with green notification energy, giant bird monster at center of light explosion, firefly UI particles fill air, 8 seconds, orchestral reveal energy, camera moves back to reveal full jungle scale, cinematic grandeur',
      negativePrompt: 'dark, flat, low energy, small scale, cartoon, cheap VFX, random colors, cluttered UI elements',
      tool: 'Midjourney + Runway + VFX',
      status: 'idea',
      notes: 'This is the payoff. Everything before this moment has been building to this.',
    },
    {
      id: 'shot-06',
      shotNumber: 6,
      duration: '6s',
      shotType: 'Wide',
      cameraAngle: 'Eye level, slightly high',
      cameraMovement: 'Slow pull back',
      location: 'Jungle — full environment',
      character: 'WhatsApp Bird Monster',
      action: 'Standing in glowing jungle, looks victorious then trapped',
      whatWeSee: 'The bird stands in the glowing jungle. It looks victorious. Then its expression changes. Confused. Then small. Then trapped in its own signal.',
      whatWeHear: 'One more ping. Then silence.',
      voiceOver: '',
      dialogue: '',
      soundEffects: 'Final single ping. Long silence. Ambient green hum.',
      musicNote: 'Single note. Fade to silence.',
      visualStyle: 'Pull back slowly. Bird shrinks in glowing frame. Epic but melancholic.',
      lighting: 'Sustained green notification glow. Slowly fading.',
      color: 'Fading green. Returning to natural tones as camera pulls back.',
      composition: 'Bird center but progressively smaller as pull back continues. Jungle surrounds.',
      imagePrompt: 'Wide shot of giant fluffy green bird monster standing alone in glowing jungle, surrounded by fading notification light and fireflies, bird looks both victorious and lost, cinematic melancholy, photorealistic, 9:16 vertical, deep environmental scale',
      videoPrompt: 'Slow pull back from bird standing in glowing jungle, bird looks victorious then its expression shifts to confusion then trapped understanding, 6 seconds, green glow fades slowly, jungle scale dwarfs the bird by end, cinematic melancholy',
      negativePrompt: 'happy ending, celebration, fast movement, scary expression, bright white light, cartoon',
      tool: 'Midjourney + Runway',
      status: 'idea',
      notes: 'The humor and the sadness must arrive at the same moment. Do not over-explain.',
    },
  ],
  prompts: [
    {
      id: 'prompt-01',
      shotId: 'shot-01',
      type: 'image',
      toolTarget: 'Midjourney',
      version: 1,
      text: 'Cinematic jungle canopy at dawn, morning mist between ancient trees, golden light rays filtering through dense foliage, massive shadow gliding across the treetops, ultra-wide establishing shot, photorealistic, vertical 9:16, deep green and gold palette, atmospheric depth --ar 9:16 --style raw --v 6',
      notes: 'Version 1 — establishing shot. Prioritize scale and atmosphere.',
    },
    {
      id: 'prompt-02',
      shotId: 'shot-02',
      type: 'image',
      toolTarget: 'Midjourney',
      version: 1,
      text: 'Giant fluffy round green bird monster flying above cinematic jungle, massive and adorable, furious expression, WhatsApp green feathers, round soft body, enormous wings, low angle hero shot looking up from jungle level, cinematic lighting, photorealistic creature design, vertical 9:16 --ar 9:16 --style raw --v 6',
      notes: 'Version 1 — must be cute NOT scary. Round shapes are critical.',
    },
    {
      id: 'prompt-03',
      shotId: 'shot-04',
      type: 'image',
      toolTarget: 'Midjourney',
      version: 1,
      text: 'Phone screen POV looking up at giant green bird beak descending from above, beak fills upper frame, cinematic jungle in background, sky visible, soft green screen glow illuminating the beak from below, extreme close-up, photorealistic, cinematic tension, vertical 9:16 --ar 9:16 --style raw --v 6',
      notes: 'The hero shot. The POV must be felt immediately.',
    },
  ],
  assets: [
    {
      id: 'asset-01',
      shotId: 'shot-01',
      assetType: 'image',
      tool: 'Midjourney',
      promptVersion: 1,
      fileName: 'shot01_jungle_establishing_v1.png',
      status: 'approved',
      problem: '',
      nextAction: 'Ready for video generation',
      approvedVersion: 'shot01_jungle_establishing_v1.png',
      notes: 'Approved after 3 iterations. The mist depth was the key.',
    },
    {
      id: 'asset-02',
      shotId: 'shot-01',
      assetType: 'video',
      tool: 'Runway',
      promptVersion: 1,
      fileName: 'shot01_jungle_establishing_motion_v1.mp4',
      status: 'needs_refinement',
      problem: 'Camera movement too fast. Shadow not reading clearly.',
      nextAction: 'Reduce camera speed. Increase shadow contrast.',
      approvedVersion: '',
      notes: 'Second attempt needed. Pacing is critical here.',
    },
    {
      id: 'asset-03',
      shotId: 'shot-02',
      assetType: 'image',
      tool: 'Midjourney',
      promptVersion: 2,
      fileName: 'shot02_bird_reveal_v2.png',
      status: 'approved',
      problem: '',
      nextAction: 'Ready for video generation',
      approvedVersion: 'shot02_bird_reveal_v2.png',
      notes: 'v1 was too scary. v2 nailed the cute-furious balance.',
    },
    {
      id: 'asset-04',
      shotId: 'shot-03',
      assetType: 'image',
      tool: 'Midjourney',
      promptVersion: 1,
      fileName: 'shot03_phone_floor_v1.png',
      status: 'generated',
      problem: 'Phone brand logo visible. Phone too bright.',
      nextAction: 'Remove logo, reduce phone glow intensity.',
      approvedVersion: '',
      notes: 'Close. Need to clean up the phone design.',
    },
    {
      id: 'asset-05',
      shotId: 'shot-04',
      assetType: 'image',
      tool: 'Midjourney',
      promptVersion: 1,
      fileName: 'shot04_beak_pov_v1.png',
      status: 'needs_refinement',
      problem: 'Beak anatomy looks wrong. Scale is off.',
      nextAction: 'Revise prompt. Add: consistent beak shape, no distortion, green feathered texture.',
      approvedVersion: '',
      notes: 'This is the hero shot. Cannot compromise on quality.',
    },
    {
      id: 'asset-06',
      shotId: 'shot-05',
      assetType: 'image',
      tool: 'Midjourney',
      promptVersion: 1,
      fileName: '',
      status: 'not_started',
      problem: '',
      nextAction: 'Begin prompting after shots 1-4 are locked.',
      approvedVersion: '',
      notes: 'Explosion shot. Will need VFX layer on top of base image.',
    },
    {
      id: 'asset-07',
      shotId: 'shot-01',
      assetType: 'sfx',
      tool: 'ElevenLabs',
      promptVersion: 1,
      fileName: 'sfx_jungle_ambience_v1.wav',
      status: 'approved',
      problem: '',
      nextAction: 'In final edit',
      approvedVersion: 'sfx_jungle_ambience_v1.wav',
      notes: 'Deep jungle ambience with receding bird calls. Works well.',
    },
    {
      id: 'asset-08',
      shotId: 'shot-05',
      assetType: 'sfx',
      tool: 'Suno',
      promptVersion: 1,
      fileName: 'sfx_notification_explosion_v1.wav',
      status: 'prompting',
      problem: '',
      nextAction: 'Need full WhatsApp ping cascade at increasing volume.',
      approvedVersion: '',
      notes: 'Key sound moment. Must feel like notification sounds scaled to orchestral.',
    },
  ],
  createdAt: '2026-05-01T09:00:00.000Z',
  updatedAt: '2026-05-30T12:00:00.000Z',
};
